name: Pixel Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate pixel contribution SVGs
        uses: haishhun/pixel-contributions@v1.5
        with:
          github_user_name: haishhun
          token: ${{ secrets.GITHUB_TOKEN }}
          compress: true
          output_path: |
            dist/pixel-contributions.svg
            dist/pixel-contributions-light.svg?color_scheme=nord
          color_scheme: github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}